apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: n8n
    helm:
      valueFiles:
      - global/values.yaml
    repoURL: https://n8n-io.github.io/n8n-helm-chart
    targetRevision: 0.23.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
