apiVersion: apps/v1
kind: Deployment
metadata:
  name: { include "slack-connector.fullname" . }
  labels:
    {- include "slack-connector.labels" . | nindent 4 }
spec:
  replicas: 1
  selector:
    matchLabels:
      {- include "slack-connector.selectorLabels" . | nindent 6 }
  template:
    metadata:
      labels:
        {- include "slack-connector.selectorLabels" . | nindent 8 }
    spec:
      containers:
        - name: slack-connector
          image: "nginx"
          ports:
            - containerPort: 80
