apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  destination:
    namespace: ollama
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ollama
    helm:
      valueFiles:
      - global/values.yaml
    repoURL: https://otwld.github.io/ollama-helm
    targetRevision: 0.1.7
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
