apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { include "ingress-nginx.fullname" . }
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ingress-nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: { include "ingress-nginx.fullname" . }
                port:
                  number: 80
