apiVersion: apps/v1
kind: Deployment
metadata:
  name: { include "telegram-bot.fullname" . }
  labels:
    {- include "telegram-bot.labels" . | nindent 4 }
spec:
  replicas: 1
  selector:
    matchLabels:
      {- include "telegram-bot.selectorLabels" . | nindent 6 }
  template:
    metadata:
      labels:
        {- include "telegram-bot.selectorLabels" . | nindent 8 }
    spec:
      containers:
        - name: telegram-bot
          image: "nginx"
          ports:
            - containerPort: 80
